### PR TITLE
Fix typo in alg.mismatch

### LINKED ISSUE #12: typo in test\algorithm\mismatch.cpp
Hi,
    I'm a developer from Visual C++ compiler team.
    As you may know, we added NanoRange to our daily RWC (real world code) testing.
    We saw a test failure and it appears to be source issue.

		std::pair<S const *, S const *> ps2
			= ranges::mismatch(ranges::begin(s1), ranges::end(s2), s2, std::equal_to<int>(), &S::i, &S::i);

    Based on the declaration of 'mismatch', 'ranges::end(s2)' is likely a typo of 'ranges::end(s1)'.
    The test passes after I change 's2' to 's1'.

### PR DESCRIPTION
**Pull request by CaseyCarter**
Fixes #12.

### CODE REVIEW

**Comment by tcbrindle** [comment]
Thanks very much (I suspect you wrote that line in the first place! :-) )

**Comment by CaseyCarter** [comment]
> Thanks very much (I suspect you wrote that line in the first place! :-) )

Nope: 'twas Eric in ericniebler/range-v3@96815b22e85579bea0a6f0be199729a0ed92e6be

**Comment by ericniebler** [comment]
> Nope: 'twas Eric in ericniebler/range-v3@96815b2

Prove it.

**Comment by CaseyCarter** [comment]
> Prove it.

I think you'll have a hard time trying to convince anyone that the projection-specific part of the test came from the libc++ test suite.

**Comment by ericniebler** [comment]
This is what I see in range-v3's tests, and in the commit to which you link:

```diff
+    std::pair<S const *, S const *> ps2
+        = ranges::mismatch(s1, s2, std::equal_to<int>(), &S::i, &S::i);
```

No mismatched begin/end iterators there. The faulty test is maybe an additional test case added by @tcbrindle.

**Comment by CaseyCarter** [comment]
> This is what I see in range-v3's tests, and in the commit to which you link:

Oh, now I understand what we're talking about. Yes, the NanoRange test is the range-v3 test with the projection test cases duplicated into both range and iterator/sentinel-pair forms. @tcbrindle presumably introduced the bug while editing the range form of this test case into the itersentinel form.

I was intimating that the line with the bug was *copied from* another line which you originally wrote, not that you introduced this particular bug. I would have harassed you far more substantially had I thought you wrote the bug. (At the very least there would have been pointing and name calling.)

**Comment by tcbrindle** [comment]
Sorry Casey, I copied this (and all the other tests) from CMCSTL2. Looks like it was introduced in this commit: https://github.com/CaseyCarter/cmcstl2/commit/e057b55fb3b4d71fd3155b81922d19de8bca8ca2

**Comment by CaseyCarter** [comment]
> Sorry Casey, I copied this (and all the other tests) from CMCSTL2. Looks like it was introduced in this commit: CaseyCarter/cmcstl2@e057b55

*NOW* let the pointing and the name-calling commence!

**Comment by ericniebler** [comment]
HAHAHA! <points finger and calls names>

**Pull request merged**
